% ============================================
% Classe: TrabalhoAcademico.cls
% Autor: Wenes Aquino - Copyright © 2025
% ============================================
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{TrabalhoAcademico}[2025/12/10 Classe Modular ABNT UFT]
\LoadClass[12pt,a4paper,oneside]{memoir}
% ============================================
% 1. PACOTES FUNDAMENTAIS
% ============================================
\RequirePackage[brazilian]{babel}
\RequirePackage{fontspec}
\RequirePackage{tikz}
\usetikzlibrary{calc}
\RequirePackage{hyperref}
\RequirePackage{lipsum}
% ============================================
% WENES - UFT (Marca TeX)
% ============================================
\newcommand{\WenesTex}{%
    Wenes%
    \raisebox{0ex}{T}\kern-0.168em%
    \raisebox{-0.5ex}{E}\kern-0.124em%
    \raisebox{0ex}{X}
}
% ============================================
\newcommand{\abnTexUFT}{%
    abn%
    \raisebox{0ex}{T}\kern-0.168em%
    \raisebox{-0.5ex}{E}\kern-0.124em%
    \raisebox{0ex}{X}%
    \raisebox{0.4ex}{-}%
    \raisebox{0.05ex}{U}\kern-0em
    \raisebox{0.05ex}{F}\kern-0em
    \raisebox{0.05ex}{T}
}
% ============================================





% =============FIM DA CLASSE==================
